name: Build and push Docker image of findPeek 

on:
  push:
    branches:
      - main
  pull_request:
    branches:  
      -main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Build Docker image
        run: |
          docker build -t togatest:latest .
          docker run -e PARAMS="1 2 3" togatest:latest
          docker run -e PARAMS="4 6 5" togatest:latest
          docker run -e PARAMS="1 2 1" togatest:latest
          

      - name: Push Docker image
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.TOKEN }}

      - name: Push Docker image - continue
        run: |
          docker push togatest:latest

