name: Build and push Docker image of findPeek 

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Build Docker image
        run: |
          docker build -t ghcr.io/Racheli-BP/togaTest:latest .
          docker run --rm  ghcr.io/Racheli-BP/togaTest:latest 1 2 3
          docker run --rm  ghcr.io/Racheli-BP/togaTest:latest 4 6 5
          docker run --rm  ghcr.io/Racheli-BP/togaTest:latest 1 2 1
          

      - name: Push Docker image
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image - continue
        run: |
          docker push ghcr.io/Racheli-BP/togatry:latest

